name: "anima doc"
on: push

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.134.0"
      - name: Build
        working-directory: ./docs
        run: hugo --minify
      - name: Checkout Docs repo
        uses: actions/checkout@v3
        with:
          repository: ceceppa/anima-doc
          path: ./docs/anima-doc
          token: ${{ secrets.TOKEN }}

      - name: Deploy
        shell: bash {0}
        run: |
          cd docs/anima-doc

          git config user.name "GitHub Actions Bot"
          git config user.email "<senesealessandro@gmail.com>"

          rm -rf *
          cp -r ../public/* .

          git add .
          git commit -m "Update docs"

          git push origin main
